name: "Extract Audit Details from FPR"
description: "Extracts vulnerability audit details from a Fortify FPR file."
inputs:
  fpr_path:
    description: "Path to the .fpr file (optional, defaults to the most recent .fpr in the current directory)"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.fpr_path }}
