name: Extract Vulnerabilities from FPR
description: A custom action to extract vulnerabilities from a Fortify FPR file using a Python script.
author: Your Name
inputs:
  fpr_file:
    description: Path to the FPR file.
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OUTPUT_PATH: "${{ github.workspace }}/output.txt"
  args:
    - "${{ inputs.fpr_file }}"

outputs:
  output_file:
    description: Path to the output file
    value: "output.txt"
